server:
  port: 8080

spring:
  profiles:
    active: default, dev
  application:
    name: password-validator-spring-api
  redis:
    host: localhost
    port: 6379
    password: 'Redis!2020'

  cache:
    type: redis
    redis:
      time-to-live: 6000


management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true

opentracing:
  jaeger:
    http-sender:
      username: admin
      password: admin
    udp-sender:
      host: localhost

password:
  validations:
    - pattern: '[a-z]+'
      message: 'A senha deve possuir no mínimo uma letra minúscula.'
    - pattern: '[A-Z]+'
      message: 'A senha deve possuir no mínimo uma letra maiúscula.'
    - pattern: '[0-9]+'
      message: 'A senha deve possuir no mínimo 1 digito.'
    - pattern: '.{9,}'
      message: 'A senha deve possuir no mínimo 9 caracteres.'
    - pattern: '^(?:([A-Za-z0-9!@#$%^&()\-+ ])(?!.*\1))*$'
      message: 'A senha não pode conter caracteres repetidos.'
    - pattern: '[@!#$%^&*()\-+]+'
      message: 'A senha deve conter no mínimo um caracter especial.'
    - pattern: '^[^\s]+$'
      message: 'A senha não deve possuir espaços em branco'
